# Generated by Django 6.0.2 on 2026-02-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
